In [1]:
# -*- coding: utf-8 -*-

'''
@Author   :   Corley Tang
@contact  :   cutercorleytd@gmail.com
@Github   :   https://github.com/corleytd
@Time     :   2023-01-09 17:18
@Project  :   Hands-on Deep Learning with PyTorch-tensor_create_index
张量（Tensor）的创建和索引
'''

# 导入所需的库
import numpy as np
import torch

# 查看版本
torch.__version__

'1.11.0'

## 1.张量的类型和转化

In [2]:
# 使用张量创建函数创建张量
t1 = torch.tensor([1, 2])  # 列表
t1

tensor([1, 2])

In [3]:
torch.tensor((1, 2))  # 元组

tensor([1, 2])

In [4]:
a = np.array((1, 2))  # 数据
t2 = torch.tensor(a)  # dtype指定张量的数据类型
t2

tensor([1, 2], dtype=torch.int32)

In [5]:
# 查看整型的默认类型：张量默认长整型、Array默认整型
a.dtype, t1.dtype, t2.dtype

(dtype('int32'), torch.int64, torch.int32)

In [6]:
# 查看浮点型的默认类型：张量默认单精度浮点型、Array默认双精度浮点型
np.array([1.1, 2.2]).dtype, torch.tensor(np.array([1.1, 2.2])).dtype, torch.tensor([1.1, 2.2]).dtype

(dtype('float64'), torch.float64, torch.float32)

In [7]:
# 布尔型
t3 = torch.tensor([True, False])
t3, t3.dtype

(tensor([ True, False]), torch.bool)

In [8]:
# 复数型
t4 = torch.tensor([1 + 2j, 2 + 3j])
t4, t4.dtype

(tensor([1.+2.j, 2.+3.j]), torch.complex64)

In [9]:
# 指定类型创建张量
torch.tensor([1, 2], dtype=torch.int16)

tensor([1, 2], dtype=torch.int16)

In [10]:
# 张量类型的隐式转化
# 整型和浮点型
t5 = torch.tensor([1.1, 2])
t5, t5.dtype

(tensor([1.1000, 2.0000]), torch.float32)

In [11]:
# 布尔型和数值型
t6 = torch.tensor([True, 2., False])
t6, t6.dtype

(tensor([1., 2., 0.]), torch.float32)

In [12]:
# 张量类型的显式转化
t1, t1.float(), t1.double(), t1.short(), t1  # 不会改变原有张量的类型

(tensor([1, 2]),
 tensor([1., 2.]),
 tensor([1., 2.], dtype=torch.float64),
 tensor([1, 2], dtype=torch.int16),
 tensor([1, 2]))

## 2.张量的维度和形变

In [13]:
# 查看张量的维度和形状
t1.ndim, t1.shape, t1.size()

(1, torch.Size([2]), torch.Size([2]))

In [14]:
# 查看低1维度的元素个数、元素总个数
len(t1), t1.numel()

(2, 2)

In [15]:
# 创建二维张量
t7 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t7

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
t7.ndim, t7.shape, t7.size(), len(t7), t7.numel()

(2, torch.Size([2, 3]), torch.Size([2, 3]), 2, 6)

In [17]:
# “零”维张量
t8 = torch.tensor(1)
t8, t8.ndim, t8.shape, t8.numel()

(tensor(1), 0, torch.Size([]), 1)

In [18]:
# 一维张量
t9 = torch.tensor([1])
t9, t9.ndim, t9.shape, t9.numel()

(tensor([1]), 1, torch.Size([1]), 1)

In [19]:
# 高维张量
a1 = np.array([[1, 2, 2], [3, 4, 4]])
a2 = np.array([[5, 6, 6], [7, 8, 8]])
t10 = torch.tensor(np.array([a1, a2]))
a1, a2, t10

(array([[1, 2, 2],
        [3, 4, 4]]),
 array([[5, 6, 6],
        [7, 8, 8]]),
 tensor([[[1, 2, 2],
          [3, 4, 4]],
 
         [[5, 6, 6],
          [7, 8, 8]]], dtype=torch.int32))

In [20]:
t10.ndim, t10.shape, len(t10), t10.numel()

(3, torch.Size([2, 2, 3]), 2, 12)

In [21]:
# 张量的形变
# flatten拉平：将任意维度张量转化为一维张量
t7, t7.flatten()

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([1, 2, 3, 4, 5, 6]))

In [22]:
t10, t10.flatten()

(tensor([[[1, 2, 2],
          [3, 4, 4]],
 
         [[5, 6, 6],
          [7, 8, 8]]], dtype=torch.int32),
 tensor([1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8], dtype=torch.int32))

In [23]:
t8, t8.flatten(), t8.flatten().ndim

(tensor(1), tensor([1]), 1)

In [24]:
# reshape方法：任意变形
t1, t1.reshape(2, 1), t1.shape, t1.reshape(2, 1).shape, t1.ndim, t1.reshape(2, 1).ndim

(tensor([1, 2]),
 tensor([[1],
         [2]]),
 torch.Size([2]),
 torch.Size([2, 1]),
 1,
 2)

In [25]:
# 转为一维张量
t1, t1.reshape(2), t1.reshape(2, ), t1.reshape(2).ndim

(tensor([1, 2]), tensor([1, 2]), tensor([1, 2]), 1)

In [26]:
# 转为二维张量
t1, t1.reshape(1, 2), t1.reshape(1, 2).ndim

(tensor([1, 2]), tensor([[1, 2]]), 2)

In [27]:
# 转为三维张量
t1, t1.reshape(1, 1, 2), t1.reshape(1, 1, 2).shape, t1.reshape(1, 2, 1), t1.reshape(1, 2, 1).ndim

(tensor([1, 2]),
 tensor([[[1, 2]]]),
 torch.Size([1, 1, 2]),
 tensor([[[1],
          [2]]]),
 3)

In [28]:
# 用reshape方法拉平高维张量
t10.reshape(-1)

tensor([1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8], dtype=torch.int32)

## 3.特殊张量的创建

In [29]:
## 1.特殊取值的张量
# 全0张量，默认浮点型
torch.zeros([2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
# 全1张量
torch.ones([2, 3, 4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [31]:
# 单位矩阵
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [32]:
# 对角矩阵
# torch.diag([1, 2])  # TypeError
t1, torch.diag(t1)

(tensor([1, 2]),
 tensor([[1, 0],
         [0, 2]]))

In [33]:
# rand：服从0-1均匀分布的张量
torch.rand(2, 3)

tensor([[0.7381, 0.4472, 0.6182],
        [0.7681, 0.2479, 0.0711]])

In [34]:
# randn：服从标准正态分布的张量
torch.randn(2, 3)

tensor([[ 1.7518,  0.3649, -1.2904],
        [ 0.9718,  0.6282, -0.8616]])

In [35]:
# normal：服从指定正态分布的张量
torch.normal(2, 3, size=(2, 3))

tensor([[2.2268, 1.3118, 7.0009],
        [4.7417, 2.2390, 6.2416]])

In [36]:
# randint：整数随机采样结果
torch.randint(1, 100, size=[3, 4])  # 左开右闭

tensor([[86, 91, 56, 72],
        [21, 15, 25, 83],
        [74, 27, 40, 55]])

In [37]:
# arange/linspace：生成数列
torch.arange(5), torch.arange(1, 10, 3)  # 左开右闭

(tensor([0, 1, 2, 3, 4]), tensor([1, 4, 7]))

In [38]:
torch.linspace(1, 10, 4)  # 左右都包含

tensor([ 1.,  4.,  7., 10.])

In [39]:
# empty：生成未初始化的指定形状矩阵
torch.empty(2, 3)

tensor([[6.7356e+22, 5.4170e-05, 1.6785e-07],
        [2.0432e+20, 3.2915e-09, 2.1060e+23]])

In [40]:
# full：根据指定形状，填充指定数值
torch.full([4, 5], 3.14)

tensor([[3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400]])

In [41]:
## 2.指定形状的张量
t1, torch.full_like(t1, 5)

(tensor([1, 2]), tensor([5, 5]))

In [42]:
# torch.randn_like(t1)  # RuntimeError，_like类型转化需要注意转化前后数据类型一致的问题
t5, torch.randn_like(t5), t10, torch.randint_like(t10, 1, 100)

(tensor([1.1000, 2.0000]),
 tensor([-0.7440, -0.2482]),
 tensor([[[1, 2, 2],
          [3, 4, 4]],
 
         [[5, 6, 6],
          [7, 8, 8]]], dtype=torch.int32),
 tensor([[[16, 27, 29],
          [67, 80, 41]],
 
         [[64, 74, 76],
          [15, 28, 83]]], dtype=torch.int32))

In [43]:
t5, torch.zeros_like(t5), torch.ones_like(t5)

(tensor([1.1000, 2.0000]), tensor([0., 0.]), tensor([1., 1.]))

## 4.张量和其他相关类型之间的转化方法

In [44]:
# .numpy方法和np.array函数：张量转化为数组
t1, t1.numpy(), np.array(t1)

(tensor([1, 2]), array([1, 2], dtype=int64), array([1, 2], dtype=int64))

In [45]:
# .tolist方法和list函数：张量转化为列表
t1.tolist(), list(t1)

([1, 2], [tensor(1), tensor(2)])

In [46]:
# .item()方法：将0维张量转化为数值
t8, t8.item()

(tensor(1), 1)

## 5.张量的深拷贝

In [47]:
t11 = torch.arange(1, 20, 2)
t12 = t11  # 浅拷贝，t12和t11二者指向相同的对象
t11[1], t11, t12

(tensor(3),
 tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]))

In [48]:
t11[1] = 30
t11, t12

(tensor([ 1, 30,  5,  7,  9, 11, 13, 15, 17, 19]),
 tensor([ 1, 30,  5,  7,  9, 11, 13, 15, 17, 19]))

In [49]:
t12[2] = 50
t11, t12

(tensor([ 1, 30, 50,  7,  9, 11, 13, 15, 17, 19]),
 tensor([ 1, 30, 50,  7,  9, 11, 13, 15, 17, 19]))

In [50]:
t13 = t11.clone()  # 深拷贝，t13指向的对象与t11不同，相当于创建了一个新的对象，只是数值相同
t13[3], t13

(tensor(7), tensor([ 1, 30, 50,  7,  9, 11, 13, 15, 17, 19]))

In [51]:
t11[3] = 70
t11, t12, t13

(tensor([ 1, 30, 50, 70,  9, 11, 13, 15, 17, 19]),
 tensor([ 1, 30, 50, 70,  9, 11, 13, 15, 17, 19]),
 tensor([ 1, 30, 50,  7,  9, 11, 13, 15, 17, 19]))